### ISSUE TITLE
Contacting Johan

### ISSUE THREAD

**Issue by dl8dtl** [dl8dtl/qsstv#1]
Hi Steve @AG7GN any chance to get me in contact with the qsstv developer?
I'm porting it to MacOS, and as part of it now also to Qt6, it would be nice to get some response from Johan.
73, Jörg

**Comment by AG7GN** [comment]
Jörg,

I don't know Johan, but his contact information is [on his website](http://users.telenet.be/on4qz/bug_comments.html).

73,

Steve
AG7GN

**Comment by dl8dtl** [comment]
Thanks for the quick response, Steve. Tried that (already in the past, and a couple of day ago), alas never got any response.

73!
